### PR TITLE
Update `DARWINIA_CRAB_LANE`

### PR DESCRIPTION
**Pull request by boundless-forest**
Some of the lanes has been abandoned, so I clean them up.

### CODE REVIEW

**Review by fewensa — APPROVED** [review]

**Comment by AurevoirXavier** [comment]
I got a plan for this a long time ago.

I hope we can start this from `[0,0,0,0]`. We can make this more clear.

**Comment by boundless-forest** [comment]
> And add the other lanes one by one in increasing order.

I do not think this it is a better idea. There could be many lanes created in the future, for example, `[0,0,0,0]` for darwinia <> crab, and `[0,0,0,0]` for pangolin <> pangoro.  You cannot tell from more lane info by an increased lane id.

Using increased number lane id, you need another place to document these numberic lane ids even in the same bridge. no one can remember these lane id numbers for a long time.

**Comment by AurevoirXavier** [comment]
I think this repository should be a global register.

No matter how you still need a document for users to tell them how to define the landid. What if their chain also starts with `da`?a

**Comment by boundless-forest** [comment]
> I think this repository should be a global register. What if their chain also starts with da? 

Actually, it is now. In the current implementation, if someone wants to add another lane between any bridge in our system, he needs to submit the lane id here, then we need to update the chain's lane verifier to open the gate for this lane id. We can do some validate lane id submission.

One benefit from the message lane id is that many events are designed to be associated with the lane id,  you can identify the event immediately if you are familiar a bit with the lane id list. I believe it's much easier for human to distinguish the message lane id than the numberic lane id.

**Comment by AurevoirXavier** [comment]
> I believe it's much easier for human to distinguish the message lane id than the numberic lane id.

We should not place too much emphasis on this. Instead, users should always read it from a better UI rather than the raw event.

Making the code's rule/style clearer is the first priority here.

**Pull request merged**
